### ISSUE TITLE
Crash in createFaceGroups

### ISSUE THREAD

**Issue by guycalledfrank** [jpcy/xatlas#30] opened 2019-07-22 11:39 UTC
Here is a model consisting of 5 triangles: https://drive.google.com/open?id=1dwuUdRA3TPoXaiiO7zZi8r08U2R6IqFy

Somehow feeding it to xatlas causes a crash. I managed to narrow the problem down to createFaceGroups() call, but it's hard to dig up deeper without knowing what the code actually does.

(Perhaps it should be (also?) posted to original thekla_atlas github?)

**Comment by jpcy** [comment] 2019-07-23 02:42
I don't have support for fbx yet in the examples, and it doesn't crash after converting to obj.

I suspect it's a precision issue creating bad geometry. Try setting `MeshDecl::epsilon` to 0 or a higher value like 0.0001.

**Comment by jpcy** [comment] 2019-07-23 10:16
I can't reproduce this loading the file with OpenFBX.

**Comment by jpcy** [comment] 2019-10-23 11:49
Closing as dead issue. Reopen if the problem still exists.

**Closed by jpcy** 2019-10-23 11:49 UTC
Labels: bug
